# - SETTINGS -
# spawn-radius: Radius around spawn in which one cannot take any damage (0 = disabled).
# spawn-protection: Radius around spawn in which spawn protection will take affect (0 = disabled).
# speed-radius: How far undeads need to be from alive player before they get speed (0 = always have speed, -1 = disabled).
# burn: Whether morphed players should burn in daylight (only applies to entities which naturally burn).
# allow-end: Whether players are able to enter an end portal.
# afk-invulnerable: Whether AFK players should be invulnerable to other players.
# pets: Pets allow undead due to certain things if an alive player (their owner) does /pet <undead> and they are near their owner.
# allow-unplaced-locking: Whether players can lock blocks which do not have any placed data.
settings:
  spawn-radius: 10
  spawn-protection: 0
  speed-radius: 50
  burn: false
  allow-end: true
  afk-invulnerable: true
  pets: false # REQUIRES RESTART
  allow-unplaced-locking: false


# - RECIPES -
# lock-tool: Whether the custom recipe for Lock Tool should be enabled. If disabled, the only way to get lock tools would be through /locktool.
# |  A| A = Amethyst Shard
# | S | S = Stick
# |S  |
#
# glow-berries: Whether the custom recipe for Glow Berries should be enabled.
# | G | G = Glowstone Dust
# |GBG| B = Sweet Berries
# | G |
#
# heart-of-the-sea: Whether the custom recipe for Heart of the Sea should be enabled.
# |LCL| L = Sea Lantern
# |CSC| S = Nether Star
# |LCL| C = Prismarine Crystals
#
# bad-omen-potion: Whether the custom recipe for Bad Omen Potion should be enabled.
# |EGE| E = Emerald Block
# |GBG| B = Glass Bottle
# |EGE| G = Gold Ingot
#
# There will soon be a way to make your own custom recipes through this file
# REQUIRES RESTART
recipes:
  lock-tool: true
  glow-berries: true
  heart-of-the-sea: true
  bad-omen-potion: true


# - UNDEAD SPAWN -
# Location where all new or undead members will spawn and respawn.
spawn:
  x: 0
  y: 110
  z: 0
  pitch: 0
  yaw: 0


# - DISCORD -
# prefix: The prefix the bot should use for Discord commands.
# bot-token: Token of the discord bot. Do not share!
# smp-chat-channel: ID of the text channel where in-game messages should be sent.
# smp-chat-topic: What the channel topic of smp-chat-channel will be. PAPI placeholders supported.
# change-log-channel: ID of the text channel where change-logs should be published.
# link-channels: IDs of the channels where users can enter their verification codes.
# muted-role: ID of the role users should be given when muted.
# linked-role: ID of the role users should be given when linked/verified.
discord:
  prefix: "-"
  bot-token: "token"
  smp-chat-channel: "000000000000000000"
  smp-chat-topic:
    - "**Online:** %server_online%/%server_max_players%"
    - "**IP:** play.commandgeek.com"
  change-log-channel: "000000000000000000"
  link-channels:
    - "000000000000000000"
    - "111111111111111111"
  muted-role: "000000000000000000"
  linked-role: "000000000000000000"


#  - TAB -
# PlaceholderAPI supported!
# header: Text to display above player tab-list.
# footer: Text to display below player tab-list.
tab:
  header:
    - "&8- &d&lGeekSMP &8-"
    - "&7Players: &5%server_online%&8/&5%server_max_players%"
    - " "
  footer:
    - " "
    - "&7TPS: &a%server_tps_1_colored% &7MSPT: &a%server_mspt%"
    - "&7RAM: &a%server_ram_used%&7/&a%server_ram_max%"


# - GROUPS -
# All groups on the server. Configure each with the options below.
#
# - Format -
# groups:
#   <name>:
#     <option>:
#
# - Options -
# color: Main color of the group. Member's names will be changed. (GOLD, AQUA, DARK_RED, etc...).
# prefix: Group prefix for name and tab-list. ("Owner", "&eStaff", etc...).
# suffix: Group suffix for name and tab-list. ("Tier 1", "&6Level 2", etc...).
# chat-color: Color of chat for the group. If none is defined the group won't be able to chat.
# translate: Whether messages from group members should translate color codes. (true, false)
# role: Discord role id a member must have to be moved to this group. Does not apply if a member is in a non-changing group.
# revive-group: Name of the group a member should be moved to when they revive. Only applies to lowest (undead) group.
#
# Lowest group is default (undead)
groups:
  owner:
    color: GREEN
    prefix: "&a&lOWNER &a"
    chat-color: "&f"
    role: "000000000000000000"
    translate: true
    status: owner
  special:
    color: AQUA
    prefix: "&b&lSPECIAL &b"
    chat-color: "&f"
    role: "000000000000000000"
    translate: true
  staff:
    color: WHITE
    prefix: "&x&b&5&8&e&f&7&lSTAFF &f"
    chat-color: "&f"
    role: "000000000000000000"
    translate: true
    status: staff

  youtuber:
    color: GRAY
    prefix: "&x&f&f&0&0&0&0&lYT &7"
    chat-color: "&f"
    role: "000000000000000000"
  guest:
    color: GRAY
    prefix: "&3&lGUEST &7"
    chat-color: "&f"
    role: "000000000000000000"

  mvp:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lMVP &7"
    chat-color: "&f"
    role: "000000000000000000"
    translate: true
  vip+:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lVIP+ &7"
    chat-color: "&f"
    role: "000000000000000000"
  vip:
    color: GRAY
    prefix: "&x&f&f&5&c&6&3&lVIP &7"
    chat-color: "&f"
    role: "000000000000000000"

  tier3:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 3 &7"
    chat-color: "&f"
    role: "000000000000000000"
    translate: true
  tier2:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 2 &7"
    chat-color: "&f"
    role: "000000000000000000"
  tier1:
    color: GRAY
    prefix: "&x&9&0&4&8&f&f&lTIER 1 &7"
    chat-color: "&f"
    role: "000000000000000000"

  revived:
    color: GRAY
    prefix: "&7"
    chat-color: "&7"
  undead:
    color: DARK_GRAY
    revive-group: "revived"


# - MORPH MENU -
# Item meta for morph selection menu
# title: Title given to the GUI
# size: Size of the menu (multiples of 9)
# items: See "Items Format" below
#
# - Items Format -
# items:
#   <number>:
#     <meta>:
#
# - Meta -
# material: Item material
# name: Item name ("Zombie", "&6Skeleton"...)
# lore: Item lore/description ("&7Strong, slow movement Speed"...)
# skull: Skull texture value ("000000000000000000000000...")
morph-menu:
  title: "&5Morph Selection"
  size: 9
  items:
    1:
      material: PLAYER_HEAD
      name: "&6Zombie"
      lore: "&7Stronger attack but slower movement speed."
      skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ=="
    2:
      material: PLAYER_HEAD
      name: "&a/verify"
      lore: "&7Are you a &dTwitch Sub &7or &cPatron&7? Do you want to access the Discord Server? No problem! Just type &a/verify &7after selecting your morph, and enter the 4 digit code in the discord server."
    3:
      material: PLAYER_HEAD
      name: "&6Skeleton"
      lore: "&7Powerful bow and faster movement speed."
      skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzAxMjY4ZTljNDkyZGExZjBkODgyNzFjYjQ5MmE0YjMwMjM5NWY1MTVhN2JiZjc3ZjRhMjBiOTVmYzAyZWIyIn19fQ=="
